metadata:
  title: "API Reference"
  weight: 1
  description: "API Reference for external secrets"
groups:
  - group: external-secrets.io
    version: v1alpha1
    metadata:
      description: "External secrets API v1alpha1"
    kinds:
      - name: ExternalSecret
        metadata:
          description: "External secrets API"